apiVersion: v1                # API version
kind: Service                 # Type of the kubernetes resource
metadata:                     
  name: <TODO_APP_NAME>    # Name of the kubernetes resource
  labels:                     # Labels that will be applied to this resource
    app: <TODO_APP_NAME>
spec:                         
  type: LoadBalancer
  selector:
    app: <TODO_APP_NAME>   # The service exposes Pods with label `app=<TODO_APP_NAME>`
  ports:                      # Forward incoming connections on port 8080 to the target port 8080
  - name: http
    port: 8080
    targetPort: 8080