apiVersion: v1                    # API version
kind: Service                     # Type of kubernetes resource 
metadata:
  name: <TODO_DB_INSTANCE>         # Name of the resource
  labels:                         # Labels that will be applied to the resource
    app: <TODO_APP_NAME>
spec:
  ports:
    - port: 3306
  selector:                       # Selects any Pod with labels `app=<TODO_APP_NAME>,tier=db`
    app: <TODO_APP_NAME>
    tier: db